### ISSUE TITLE
Not an issue more of a question

### ISSUE THREAD

**Issue by JackinSac** [BrainStone/TMStar#1]
I'm very interested in this and wanted to try to use it, but I have no idea on how use this, I thought maybe the way to run it was to run gradlew.bat but after it loading it closed itself and now I have no idea how to choose a map for it to pathfind. Some instructions would be great, my Discord is: MyDogLovesVR#5222

**Comment by BrainStone** [comment]
As of now this project isn't finished. Or usable.
